Add how to add other language apart from Japanese
themoeway/local-audio-yomichan pull request #30
Opened 2024-05-22 17:17 UTC by foxmean

Anyway, Cristian said in discord server that this plugin only work for 1 language. So, should we mentioned about it too? (Not mention yet).

2024-05-23 02:36 UTC, cristian428 commented
I got Chinese audio files from forvo working through this add on but i had to move all the files to the same folder [forvo_files] where the japanese user folders also are. Especially since Chinese and even many other languages are now being supported by Yomitan, would it be possible to update this add on to have a separate source/folder for other languages like for chinese "zh forvo" or something like that? That way we can just specify in yomitan in the custom url json "language=zh" to only fetch the chinese files. Or at least can you add instructions for how to separate language folders for forvo in the add ons folder?  The way it is now, I need to specify all the chinese speakers with forvo usernames in the custom url.

2024-06-08 00:45 UTC, MarvNC requested changes

2024-06-08 00:45 UTC, MarvNC commented on README.md
> +        > -   **For people who learn Japanese, download the files from [this torrent](https://nyaa.si/view/1681655)**.
```suggestion
        > -   **For Japanese audio, download the files from [this torrent](https://nyaa.si/view/1681655)**.
```

2024-06-08 00:45 UTC, MarvNC commented on README.md
> +        > -   **For people who learn other language**, use the magnet link below and select to download _only_ zip file of the language under the folder Forvo_pronunciation > export > opus > [iso 639
```suggestion
        > -   **For audio of other languages**, use the magnet link below containing Forvo audio and select the zip file of the language you want under the folder `Forvo_pronunciation > export > opus > [iso 639 code of language that you want to learn.zip](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes)`:
```

2024-06-08 00:45 UTC, MarvNC commented on README.md
> +        > -   **For people who learn Japanese, download the files from [this torrent](https://nyaa.si/view/1681654)**.
```suggestion
        > -   **For Japanese audio, download the files from [this torrent](https://nyaa.si/view/1681654)**.
```

2024-06-08 00:45 UTC, MarvNC commented on README.md
> +        >     </details>
Why is this repeated twice? Is the audio in the torrent mp3 or ogg?

2024-06-08 00:45 UTC, MarvNC commented on README.md
> +2. Extract the `.tar.xz` (Japanese), or `.zip` file for other language.
```suggestion
2. Extract the `.tar.xz` (Japanese), or `.zip` file for other languages.
```

2024-06-08 00:45 UTC, MarvNC commented on README.md
> +    * For people who learn Japanese, copy the entire `user_files` folder (from the second step) into this folder.
```suggestion
    * For Japanese, copy the entire `user_files` folder (from the second step) into this folder.
```

2024-06-08 00:45 UTC, MarvNC commented on README.md
> +        <details> <summary>Expected file structure for people who learn Japanese <i>(click here)</i></summary>
```suggestion
        <details> <summary>Expected file structure for Japanese audio <i>(click here)</i></summary>
```

2024-06-08 00:45 UTC, MarvNC commented on README.md
> +    * For people who learn other language: change the name of folder from the second step to `forvo_files` and copy the entire folder _into_ `user_files` folder.
```suggestion
    * For other languages, change the name of the folder from the second step to `forvo_files` and copy the entire folder _into_ the `user_files` folder.
```

2024-06-08 00:45 UTC, MarvNC commented on README.md
> +        <details> <summary>Example file structure for people who learn other language <i>(click here)</i></summary>
```suggestion
        <details> <summary>Example file structure for other languages' audio <i>(click here)</i></summary>
```

2024-07-29 05:01 UTC, MarvNC commented on README.md
> +        > -   **For people who learn other language**, use the magnet link below and select to download _only_ zip file of the language under the folder Forvo_pronunciation > export > mp3 > [iso 639
```suggestion
        > -   **For audio of other languages**, use the magnet link below containing Forvo audio and select the zip file of the language you want under the folder `Forvo_pronunciation > export > opus > [iso 639 code of language that you want to learn.zip](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes)`:
```

2024-07-29 05:02 UTC, MarvNC approved these changes
I think the overall structure of the readme might need a little more organization but that can come in a later PR.

2024-08-11 20:12 UTC, jamesmaa approved these changes

2024-08-11 20:12 UTC, merged

2025-03-05 11:35 UTC, Geniusssmit commented
> I got Chinese audio files from forvo working through this add on but i had to move all the files to the same folder [forvo_files] where the japanese user folders also are. Especially since Chinese and even many other languages are now being supported by Yomitan, would it be possible to update this add on to have a separate source/folder for other languages like for chinese "zh forvo" or something like that? That way we can just specify in yomitan in the custom url json "language=zh" to only fetch the chinese files. Or at least can you add instructions for how to separate language folders for forvo in the add ons folder?  The way it is now, I need to specify all the chinese speakers with forvo usernames in the custom url.

Where can I download files for Mandarin Chinese? I you have them, please share :)